"""Synthesize a v3 frontmatter baseline for docs that have none.

Companion to ``migrate_frontmatter_v3.py``. The original tool handles
``schema_version: 2 -> 3`` transformation but skips docs without any
frontmatter block. The Phase 8 corpus reality (verified 2026-05-05) is:

    schema_version: 3                = 69
    schema_version: 2                = 1
    no frontmatter (legacy authoring) = 1,713  (body-level
                                                 retrieval-anchor-keywords:)
    no frontmatter, no anchors        = ~503

So 2,200+ docs need a v3 frontmatter created from scratch. That work
splits into two passes:

  1. **deterministic baseline** (this module) — fields that can be
     derived from filename / category / body / legacy fields without
     any LLM judgement: schema_version, title, concept_id, category,
     difficulty, doc_role (heuristic), level, language, source_priority,
     aliases (lifted from retrieval-anchor-keywords), intents
     (default-by-role).

  2. **authorial fields** (separate codex-worker step) — fields that
     require concept understanding: mission_ids, review_feedback_tags,
     symptoms, prerequisites, next_docs, linked_paths (beyond mechanical
     relative-link lift), confusable_with, forbidden_neighbors,
     expected_queries, contextual_chunk_prefix.

This module's output is a v3 frontmatter dict where authorial fields
are present-but-empty so the worker can fill them with strict diff
review. ``contextual_chunk_prefix`` is intentionally left empty here
and is generated by a separate per-chunk worker (see
``synthesize_chunk_prefix.py``).

Idempotent: if a doc already has any frontmatter block, the file is
skipped — it must go through ``migrate_frontmatter_v3.py`` (v2 -> v3)
or be hand-edited (v3 -> v3 refinement).

Usage::

    .venv/bin/python -m scripts.learning.rag.r3.create_v3_frontmatter \\
        --paths knowledge/cs/contents/algorithm \\
        --apply

Default mode is ``--dry-run``: prints the plan without writing.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

try:
    import yaml
except ImportError as exc:  # pragma: no cover
    raise SystemExit(
        "PyYAML is required for create_v3_frontmatter "
        "(install via `.venv/bin/python -m pip install pyyaml`)"
    ) from exc

from scripts.learning.rag.r3.migrate_frontmatter_v3 import (
    DEFAULT_INTENTS_BY_ROLE,
    DEFAULT_SOURCE_PRIORITY,
    V3_FIELD_ORDER,
    derive_category,
    detect_language,
    serialize_v3_frontmatter,
)


# ---------------------------------------------------------------------------
# Heuristics
# ---------------------------------------------------------------------------

# doc_role mapping by filename suffix / pattern. Order matters: first
# match wins. Patterns are matched against the kebab-case stem (filename
# without the .md extension), not the path.
DOC_ROLE_HEURISTICS: tuple[tuple[re.Pattern[str], str], ...] = (
    # Order matters — first match wins. Keep more-specific suffixes
    # before more-general ones (e.g. `-mission-bridge` must precede
    # `-bridge`).
    (re.compile(r"-mission-bridge$"), "mission_bridge"),
    (re.compile(r"-symptom-router$"), "symptom_router"),
    (re.compile(r"-case-study$"), "playbook"),
    (re.compile(r"-mini-card$"), "drill"),
    (re.compile(r"-cheat-sheet$"), "drill"),
    (re.compile(r"-decision-matrix$"), "chooser"),
    (re.compile(r"-internals$"), "deep_dive"),
    (re.compile(r"-deep-dive$"), "deep_dive"),
    (re.compile(r"-(primer|basics|foundations|introduction|entrypoint)$"),
     "primer"),
    # `-bridge$` precedes the `-vs-` chooser pattern: a filename that
    # ends in `-bridge` is connecting two concepts (bridge), not
    # presenting a A-vs-B comparison decision (chooser). Production v3
    # docs (e.g. dao-vs-repository-bridge.md) confirm the intent.
    (re.compile(r"-bridge$"), "bridge"),
    (re.compile(r"-(vs|chooser|selector)-"), "chooser"),
)

DEFAULT_DOC_ROLE = "primer"


DIFFICULTY_LABEL_RE = re.compile(
    r"\*\*난이도:\s*[🟢🟡🔴]?\s*(Beginner|Intermediate|Advanced|Expert)\*\*",
    re.IGNORECASE,
)

DIFFICULTY_TO_LEVEL: dict[str, str] = {
    "beginner": "beginner",
    "intermediate": "intermediate",
    "advanced": "advanced",
    "expert": "advanced",  # v3 enum has no 'expert', fold to advanced
}

H1_RE = re.compile(r"^#\s+(.+?)\s*$", re.MULTILINE)
ANCHORS_RE = re.compile(
    r"^retrieval-anchor-keywords:\s*(.+?)\s*$", re.MULTILINE
)
RELATED_DOCS_BLOCK_RE = re.compile(
    r"^관련\s*문서:\s*\n(?:\s*\n)?((?:^[-*]\s+.+\n?)+)",
    re.MULTILINE,
)
RELATIVE_LINK_RE = re.compile(r"\]\(([^)]+\.md)\)")


def _extract_h1(body: str) -> str | None:
    m = H1_RE.search(body)
    return m.group(1).strip() if m else None


def _extract_difficulty_label(body: str) -> str | None:
    m = DIFFICULTY_LABEL_RE.search(body)
    return m.group(1).strip().lower() if m else None


def _extract_aliases(body: str) -> list[str]:
    m = ANCHORS_RE.search(body)
    if not m:
        return []
    raw = m.group(1)
    items = [item.strip() for item in raw.split(",")]
    seen: set[str] = set()
    out: list[str] = []
    for item in items:
        if not item:
            continue
        norm = item.lower()
        if norm in seen:
            continue
        seen.add(norm)
        out.append(norm)
    return out


def _extract_linked_paths(body: str, file_path: Path) -> list[str]:
    """Lift relative .md links from the '관련 문서:' block.

    Returns repo-relative paths (knowledge/cs/contents/...).
    """
    block_match = RELATED_DOCS_BLOCK_RE.search(body)
    if not block_match:
        return []
    block = block_match.group(1)
    out: list[str] = []
    seen: set[str] = set()
    for link_match in RELATIVE_LINK_RE.finditer(block):
        href = link_match.group(1).strip()
        if href.startswith("http"):
            continue
        # README.md links are navigation, not retrieval candidates.
        if href.endswith("README.md"):
            continue
        try:
            resolved = (file_path.parent / href).resolve()
        except OSError:
            continue
        try:
            rel = resolved.relative_to(file_path.parent.parent.parent.parent)
        except ValueError:
            # Outside repo — keep the raw href.
            rel = Path(href)
        rel_str = rel.as_posix()
        if rel_str in seen:
            continue
        seen.add(rel_str)
        out.append(rel_str)
    return out


def _doc_role_for_stem(stem: str) -> str:
    for pattern, role in DOC_ROLE_HEURISTICS:
        if pattern.search(stem):
            return role
    return DEFAULT_DOC_ROLE


def _concept_id_for_path(file_path: Path) -> str:
    category = derive_category(file_path) or "uncategorized"
    stem = file_path.stem
    # concept_id pattern: '^[a-z][a-z0-9-]*\\/[a-z][a-z0-9-]+$'
    safe_stem = re.sub(r"[^a-z0-9-]+", "-", stem.lower()).strip("-")
    if not safe_stem:
        safe_stem = "doc"
    if not safe_stem[0].isalpha():
        safe_stem = "x-" + safe_stem
    safe_cat = re.sub(r"[^a-z0-9-]+", "-", category.lower()).strip("-")
    return f"{safe_cat}/{safe_stem}"


# ---------------------------------------------------------------------------
# Synthesis
# ---------------------------------------------------------------------------

@dataclass
class SynthesisResult:
    file_path: Path
    skipped: bool
    skipped_reason: str | None = None
    synthesized: bool = False
    new_frontmatter: dict | None = None
    new_text: str | None = None


_FRONTMATTER_OPEN_RE = re.compile(r"\A---\s*\n")


def synthesize_v3_frontmatter(file_path: Path, body: str) -> dict:
    """Synthesize a deterministic v3 frontmatter from a body-only doc.

    Returns a dict in canonical V3_FIELD_ORDER. Authorial fields are
    present-but-empty (empty list / empty string) so the next stage
    (codex worker) can fill them via diff review.
    """
    title = _extract_h1(body) or file_path.stem.replace("-", " ").title()
    difficulty = _extract_difficulty_label(body)
    role = _doc_role_for_stem(file_path.stem)
    level = DIFFICULTY_TO_LEVEL.get(difficulty or "", "intermediate")
    aliases = _extract_aliases(body)
    linked_paths = _extract_linked_paths(body, file_path)

    fm: dict = {
        "schema_version": 3,
        "title": title,
        "concept_id": _concept_id_for_path(file_path),
        # primers default canonical=true; lint catches multi-canonical
        # violations per concept_id later. matches migrate_frontmatter_v3 §6.
        "canonical": role == "primer",
        "category": derive_category(file_path) or "uncategorized",
        # difficulty stored lowercase to match Pilot v3 docs.
        "difficulty": (difficulty or ""),
        "doc_role": role,
        "level": level,
        "language": detect_language(body),
        "source_priority": DEFAULT_SOURCE_PRIORITY.get(role, 80),
        "mission_ids": [],
        "review_feedback_tags": [],
        "aliases": aliases,
        "symptoms": [],
        "intents": list(DEFAULT_INTENTS_BY_ROLE.get(role, ["definition"])),
        "prerequisites": [],
        "next_docs": [],
        "linked_paths": linked_paths,
        "confusable_with": [],
        "forbidden_neighbors": [],
        "expected_queries": [],
        "contextual_chunk_prefix": "",
    }
    return fm


def synthesize_file(file_path: Path) -> SynthesisResult:
    text = file_path.read_text(encoding="utf-8")
    if _FRONTMATTER_OPEN_RE.match(text):
        return SynthesisResult(
            file_path=file_path, skipped=True,
            skipped_reason="already has frontmatter — use migrate_frontmatter_v3 instead",
        )
    fm = synthesize_v3_frontmatter(file_path, text)
    yaml_block = serialize_v3_frontmatter(fm).rstrip("\n")
    new_text = f"---\n{yaml_block}\n---\n{text}"
    return SynthesisResult(
        file_path=file_path,
        skipped=False,
        synthesized=True,
        new_frontmatter=fm,
        new_text=new_text,
    )


def discover_md_files(roots: Iterable[Path]) -> list[Path]:
    out: list[Path] = []
    for root in roots:
        if root.is_file() and root.suffix == ".md":
            out.append(root)
        elif root.is_dir():
            out.extend(sorted(root.rglob("*.md")))
    seen: set[Path] = set()
    deduped: list[Path] = []
    for p in out:
        if p not in seen:
            seen.add(p)
            deduped.append(p)
    return deduped


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="create_v3_frontmatter",
        description="Synthesize v3 frontmatter for docs that have none.",
    )
    parser.add_argument(
        "--paths", nargs="+", required=True, type=Path,
        help="One or more .md files or directories to scan.",
    )
    parser.add_argument(
        "--apply", action="store_true",
        help="Write changes. Default is dry-run (no writes).",
    )
    parser.add_argument(
        "--quiet", action="store_true",
        help="Suppress per-file output; only print summary.",
    )
    parser.add_argument(
        "--lock-file",
        type=Path,
        default=Path("config/migration_v3/locked_pilot_paths.json"),
        help="Lock file listing v3 docs that must not be touched.",
    )
    args = parser.parse_args(argv)

    locked: set[str] = set()
    if args.lock_file.exists():
        import json
        payload = json.loads(args.lock_file.read_text(encoding="utf-8"))
        locked = {str(p) for p in payload.get("locked_paths", [])}

    files = discover_md_files(args.paths)
    if not files:
        print("no markdown files found", file=sys.stderr)
        return 1

    summary = {
        "scanned": 0,
        "synthesized": 0,
        "skipped_locked": 0,
        "skipped_has_frontmatter": 0,
        "skipped_other": 0,
    }
    for f in files:
        summary["scanned"] += 1
        rel = f.as_posix()
        if rel in locked:
            summary["skipped_locked"] += 1
            if not args.quiet:
                print(f"  [lock] {rel} — Pilot v3 (skip)")
            continue
        result = synthesize_file(f)
        if result.skipped:
            if "frontmatter" in (result.skipped_reason or ""):
                summary["skipped_has_frontmatter"] += 1
            else:
                summary["skipped_other"] += 1
            if not args.quiet:
                print(f"  [skip {f}] {result.skipped_reason}")
            continue
        summary["synthesized"] += 1
        if not args.quiet:
            badge = "[apply]" if args.apply else "[dry-run]"
            role = (result.new_frontmatter or {}).get("doc_role", "?")
            level = (result.new_frontmatter or {}).get("level", "?")
            n_aliases = len((result.new_frontmatter or {}).get("aliases", []))
            print(f"  {badge} {f}: doc_role={role} level={level} "
                  f"aliases={n_aliases}")
        if args.apply:
            f.write_text(result.new_text or "", encoding="utf-8")

    print()
    print(f"scanned: {summary['scanned']}")
    print(f"synthesized: {summary['synthesized']}"
          + (" (would-be in dry-run)" if not args.apply else ""))
    print(f"skipped: locked={summary['skipped_locked']} "
          f"has_frontmatter={summary['skipped_has_frontmatter']} "
          f"other={summary['skipped_other']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
