"""Auto-migrate corpus v2 frontmatter to v3 contract.

Companion to docs/worklogs/rag-r3-corpus-v3-contract.md and
docs/worklogs/rag-r3-pilot-50-docs-selection.md.

Reads each ``.md`` file under ``corpus_root``, parses its frontmatter,
and — if ``schema_version: 2`` — transforms it to ``schema_version: 3``
per the rules in this module. Body content is byte-preserved; only the
frontmatter region (between the leading ``---`` markers) is rewritten.

Transformation rules (Wave A automation; see contract §8.4):

    1. ``schema_version: 2`` → ``schema_version: 3``
    2. ``doc_role`` mapping for v2-only values:
         comparison → bridge
       (primer / chooser / bridge / deep_dive / playbook / drill stay)
    3. ``category`` derived from folder placement under ``contents/``.
    4. ``language`` derived from CJK character ratio in the body
       (≥30% → ``ko``; >0% → ``mixed``; 0% → ``en``).
    5. ``source_priority`` default by doc_role:
         primer 90 / chooser 88 / bridge 85 / deep_dive 80 /
         playbook 78 / drill 75 / symptom_router 80 / mission_bridge 78.
    6. ``canonical`` defaults to True for primer docs (assumes single-
       primer-per-concept; the lint catches multi-canonical violations).
    7. v2 ``acceptable_neighbors`` + ``companion_neighbors`` → ``linked_paths``
       (deduplicated). v3 keeps ``acceptable_paths`` for the qrel side
       only; the corpus contract treats neighbor docs as graph metadata.
    8. v2 ``forbidden_neighbors`` is preserved as-is.
    9. ``aliases`` and ``expected_queries`` are forced disjoint:
       any phrase in ``expected_queries`` whose case-folded /
       whitespace-normalized form matches an alias is removed from
       ``expected_queries``. (Enforces the v3 structural defense
       against the circular-leak class of bug.)
    10. ``intents`` defaulted by doc_role when absent (heuristic).
    11. ``contextual_chunk_prefix`` is NOT auto-generated by this tool
        (requires an LLM call; deferred to Phase 5 indexer or per-doc
        manual authoring).

The tool is idempotent: re-running on a v3 doc is a no-op.

Output is deterministic — fields are written in the canonical v3 order
defined by ``V3_FIELD_ORDER`` so diffs are reviewable.

Usage::

    .venv/bin/python -m scripts.learning.rag.r3.migrate_frontmatter_v3 \\
        --paths knowledge/cs/contents \\
        --apply

Default mode is ``--dry-run``: prints the transform plan without writing
any files. Always pair with ``corpus_lint`` afterwards.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

try:
    import yaml  # PyYAML, available in .venv (verified 6.0.3)
except ImportError as exc:  # pragma: no cover
    raise SystemExit(
        "PyYAML is required for migrate_frontmatter_v3 "
        "(install via `.venv/bin/python -m pip install pyyaml`)"
    ) from exc


# ---------------------------------------------------------------------------
# Transformation rules
# ---------------------------------------------------------------------------

V2_DOC_ROLE_TO_V3: dict[str, str] = {
    # v2 had a "comparison" role; v3 enum reframes it as "bridge".
    "comparison": "bridge",
}

# Default source_priority by v3 doc_role. Higher = more authoritative
# citation source (see contract §2.2.8).
DEFAULT_SOURCE_PRIORITY: dict[str, int] = {
    "primer": 90,
    "chooser": 88,
    "bridge": 85,
    "deep_dive": 80,
    "playbook": 78,
    "drill": 75,
    "symptom_router": 80,
    "mission_bridge": 78,
}

# Default intents by doc_role (heuristic; authors can override).
DEFAULT_INTENTS_BY_ROLE: dict[str, list[str]] = {
    "primer": ["definition"],
    "chooser": ["comparison", "design"],
    "bridge": ["comparison"],
    "deep_dive": ["deep_dive"],
    "playbook": ["troubleshooting", "design"],
    "drill": ["drill"],
    "symptom_router": ["symptom"],
    "mission_bridge": ["mission_bridge"],
}

# Canonical v3 field order (deterministic frontmatter rendering).
V3_FIELD_ORDER: tuple[str, ...] = (
    "schema_version",
    "title",
    "concept_id",
    "canonical",
    "category",
    "difficulty",
    "doc_role",
    "level",
    "language",
    "source_priority",
    "mission_ids",
    "review_feedback_tags",
    "aliases",
    "symptoms",
    "intents",
    "prerequisites",
    "next_docs",
    "linked_paths",
    "confusable_with",
    "forbidden_neighbors",
    "expected_queries",
    "contextual_chunk_prefix",
)


_FRONTMATTER_BLOCK_RE = re.compile(
    r"\A(---\s*\n)(.*?)(\n---\s*\n)", re.DOTALL
)
_HANGUL_RE = re.compile(r"[가-힣]")  # Korean syllables
_HAN_RE = re.compile(r"[一-鿿]")     # CJK Unified Ideographs


def detect_language(body: str) -> str:
    """Return ``ko`` / ``mixed`` / ``en`` based on CJK character ratio.

    Empty body → ``en``. Pure-ASCII body → ``en``. Korean/CJK > 30% of
    characters → ``ko``. Non-zero but ≤ 30% → ``mixed``.
    """
    if not body:
        return "en"
    cjk_count = (
        len(_HANGUL_RE.findall(body)) + len(_HAN_RE.findall(body))
    )
    ratio = cjk_count / len(body)
    if ratio >= 0.3:
        return "ko"
    if ratio > 0:
        return "mixed"
    return "en"


def derive_category(file_path: Path) -> str | None:
    """Walk path to find the parent directly under ``contents/``."""
    parts = file_path.as_posix().split("/")
    if "contents" in parts:
        idx = parts.index("contents")
        if idx + 1 < len(parts):
            return parts[idx + 1]
    return None


def _normalize_phrase(s: str) -> str:
    return re.sub(r"\s+", " ", s.strip().casefold())


def _drop_aliases_from_expected_queries(
    aliases: list[str] | None,
    expected_queries: list[str] | None,
) -> tuple[list[str], list[str], list[str]]:
    """Returns ``(aliases_kept, expected_queries_kept, removed_overlaps)``.

    Aliases are kept verbatim. Expected queries whose normalized form
    matches an alias are dropped (preserves the v3 disjoint invariant).
    """
    aliases_kept = list(aliases or [])
    expected_kept: list[str] = []
    removed: list[str] = []
    norm_aliases = {_normalize_phrase(a) for a in aliases_kept if isinstance(a, str)}
    for q in (expected_queries or []):
        if not isinstance(q, str):
            continue
        if _normalize_phrase(q) in norm_aliases:
            removed.append(q)
        else:
            expected_kept.append(q)
    return aliases_kept, expected_kept, removed


# ---------------------------------------------------------------------------
# Migration
# ---------------------------------------------------------------------------

@dataclass
class MigrationResult:
    file_path: Path
    skipped: bool
    skipped_reason: str | None = None
    transformed: bool = False
    overlaps_removed: list[str] | None = None
    new_frontmatter: dict | None = None
    new_text: str | None = None


def transform_v2_to_v3(
    v2_fm: dict,
    file_path: Path,
    body: str,
) -> tuple[dict, list[str]]:
    """Transform a parsed v2 frontmatter dict to a v3 dict.

    Returns ``(v3_fm, overlaps_removed)``. Body is read-only; this
    function does not modify text.
    """
    new_fm: dict = dict(v2_fm)

    # 1. schema_version
    new_fm["schema_version"] = 3

    # 2. doc_role mapping (legacy v2 → v3 enum)
    role = new_fm.get("doc_role")
    if role in V2_DOC_ROLE_TO_V3:
        new_fm["doc_role"] = V2_DOC_ROLE_TO_V3[role]
        role = new_fm["doc_role"]

    # 3. category derivation
    if not new_fm.get("category"):
        cat = derive_category(file_path)
        if cat:
            new_fm["category"] = cat

    # 4. language detection
    if not new_fm.get("language"):
        new_fm["language"] = detect_language(body)

    # 5. source_priority default
    if not new_fm.get("source_priority"):
        new_fm["source_priority"] = DEFAULT_SOURCE_PRIORITY.get(role or "", 80)

    # 6. canonical default for primers
    if "canonical" not in new_fm:
        new_fm["canonical"] = role == "primer"

    # 7. acceptable_neighbors + companion_neighbors → linked_paths
    legacy_neighbors = []
    for legacy_field in ("acceptable_neighbors", "companion_neighbors"):
        items = v2_fm.get(legacy_field) or []
        if isinstance(items, list):
            legacy_neighbors.extend(s for s in items if isinstance(s, str))
    if legacy_neighbors:
        existing = new_fm.get("linked_paths") or []
        if not isinstance(existing, list):
            existing = []
        merged = list(dict.fromkeys(list(existing) + legacy_neighbors))
        new_fm["linked_paths"] = merged
    # Drop legacy keys after promotion
    new_fm.pop("acceptable_neighbors", None)
    new_fm.pop("companion_neighbors", None)

    # 8. forbidden_neighbors preserved
    # (no-op; kept as-is by dict copy)

    # 9. aliases ⊥ expected_queries enforcement
    aliases_kept, eq_kept, overlaps = _drop_aliases_from_expected_queries(
        new_fm.get("aliases"), new_fm.get("expected_queries")
    )
    new_fm["aliases"] = aliases_kept
    new_fm["expected_queries"] = eq_kept

    # 10. intents default by doc_role
    if "intents" not in new_fm or not new_fm.get("intents"):
        new_fm["intents"] = list(DEFAULT_INTENTS_BY_ROLE.get(role or "", ["definition"]))

    return new_fm, overlaps


def serialize_v3_frontmatter(fm: dict) -> str:
    """Deterministic v3 frontmatter YAML rendering.

    Fields are written in V3_FIELD_ORDER first, then any remaining keys
    in their original insertion order. Non-ASCII characters are
    preserved (Korean strings).
    """
    ordered: dict = {}
    for key in V3_FIELD_ORDER:
        if key in fm:
            ordered[key] = fm[key]
    for key, value in fm.items():
        if key not in ordered:
            ordered[key] = value

    return yaml.dump(
        ordered,
        allow_unicode=True,
        sort_keys=False,
        default_flow_style=False,
        width=10000,  # avoid line-wrapping long aliases
    )


def migrate_file(file_path: Path) -> MigrationResult:
    """Migrate one .md file's frontmatter from v2 to v3.

    Idempotent: v3 docs are skipped. No-frontmatter docs are skipped.
    """
    text = file_path.read_text(encoding="utf-8")
    m = _FRONTMATTER_BLOCK_RE.match(text)
    if not m:
        return MigrationResult(
            file_path=file_path, skipped=True,
            skipped_reason="no frontmatter block",
        )

    open_marker, body_yaml, close_marker = m.groups()
    rest = text[m.end():]

    try:
        v2_fm = yaml.safe_load(body_yaml) or {}
    except yaml.YAMLError as exc:
        return MigrationResult(
            file_path=file_path, skipped=True,
            skipped_reason=f"yaml parse error: {exc}",
        )

    if not isinstance(v2_fm, dict):
        return MigrationResult(
            file_path=file_path, skipped=True,
            skipped_reason=f"frontmatter is not a mapping ({type(v2_fm).__name__})",
        )

    schema_version = str(v2_fm.get("schema_version", ""))
    if schema_version == "3":
        return MigrationResult(
            file_path=file_path, skipped=True,
            skipped_reason="already schema_version: 3",
        )
    if schema_version != "2":
        return MigrationResult(
            file_path=file_path, skipped=True,
            skipped_reason=f"unsupported schema_version: {schema_version!r}",
        )

    new_fm, overlaps = transform_v2_to_v3(v2_fm, file_path, rest)
    new_yaml = serialize_v3_frontmatter(new_fm)
    # Trim trailing newline from yaml.dump; we re-append exact close marker.
    new_yaml = new_yaml.rstrip("\n")
    new_text = f"{open_marker}{new_yaml}{close_marker}{rest}"

    return MigrationResult(
        file_path=file_path,
        skipped=False,
        transformed=True,
        overlaps_removed=overlaps,
        new_frontmatter=new_fm,
        new_text=new_text,
    )


def discover_md_files(roots: Iterable[Path]) -> list[Path]:
    out: list[Path] = []
    for root in roots:
        if root.is_file() and root.suffix == ".md":
            out.append(root)
        elif root.is_dir():
            out.extend(sorted(root.rglob("*.md")))
    # dedupe preserving order
    seen: set[Path] = set()
    deduped: list[Path] = []
    for p in out:
        if p not in seen:
            seen.add(p)
            deduped.append(p)
    return deduped


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="migrate_frontmatter_v3",
        description="Auto-migrate corpus v2 frontmatter to v3 contract.",
    )
    parser.add_argument(
        "--paths", nargs="+", required=True, type=Path,
        help="One or more .md files or directories to scan.",
    )
    parser.add_argument(
        "--apply", action="store_true",
        help="Write changes. Default is dry-run (no writes).",
    )
    parser.add_argument(
        "--quiet", action="store_true",
        help="Suppress per-file output; only print summary.",
    )
    args = parser.parse_args(argv)

    files = discover_md_files(args.paths)
    if not files:
        print("no markdown files found", file=sys.stderr)
        return 1

    summary = {
        "scanned": 0,
        "transformed": 0,
        "skipped_v3": 0,
        "skipped_no_fm": 0,
        "skipped_other": 0,
        "overlaps_removed_total": 0,
    }
    for f in files:
        result = migrate_file(f)
        summary["scanned"] += 1
        if result.skipped:
            if result.skipped_reason == "already schema_version: 3":
                summary["skipped_v3"] += 1
            elif result.skipped_reason == "no frontmatter block":
                summary["skipped_no_fm"] += 1
            else:
                summary["skipped_other"] += 1
                if not args.quiet:
                    print(f"  [skip {f}] {result.skipped_reason}")
            continue
        summary["transformed"] += 1
        n_overlaps = len(result.overlaps_removed or [])
        summary["overlaps_removed_total"] += n_overlaps
        if not args.quiet:
            badge = "[apply]" if args.apply else "[dry-run]"
            print(f"  {badge} {f}: v2→v3"
                  + (f" (removed {n_overlaps} alias-overlap from expected_queries)"
                     if n_overlaps else ""))
        if args.apply:
            f.write_text(result.new_text or "", encoding="utf-8")

    print()
    print(f"scanned: {summary['scanned']}")
    print(f"transformed: {summary['transformed']}"
          + (" (would-be in dry-run)" if not args.apply else ""))
    print(f"skipped: v3={summary['skipped_v3']} "
          f"no_fm={summary['skipped_no_fm']} "
          f"other={summary['skipped_other']}")
    print(f"alias-overlap removed from expected_queries: "
          f"{summary['overlaps_removed_total']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
